apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - vcluster-1
  - vcluster-2
  - vcluster-3
  - vcluster-4
  - vcluster-5
  - vcluster-6
  - vcluster-7
  - vcluster-8
  - vcluster-9
  - vcluster-10
  - vcluster-11
  - vcluster-12
  - vcluster-13
  - vcluster-14
  - vcluster-15
  - vcluster-16
  - vcluster-17
  - vcluster-18
  - vcluster-19
  - vcluster-20
  - vcluster-21
  - vcluster-22
  - vcluster-23
  - vcluster-24
