apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helm-repository.yaml
  - helm-release-otel-operator.yaml
  - otel-operator-rbac.yaml
  - helm-release-prometheus-crds.yaml
