apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opentelemetry-operator-extra
rules:
  - apiGroups: [""]
    resources:
      - nodes/proxy
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: opentelemetry-operator-extra
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: opentelemetry-operator-extra
subjects:
  - kind: ServiceAccount
    name: opentelemetry-operator
    namespace: monitoring
