apiVersion: v1
kind: Namespace
metadata:
  name: ns-01
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-02
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-03
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-04
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-05
