apiVersion: v1
kind: Namespace
metadata:
  name: workshop-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: workshop-participant
  namespace: workshop-system
---
apiVersion: v1
kind: Secret
metadata:
  name: workshop-participant-token
  namespace: workshop-system
  annotations:
    kubernetes.io/service-account.name: workshop-participant
type: kubernetes.io/service-account-token
