apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: testkube-api-server
  namespace: testkube
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: api-server
  podMetricsEndpoints:
    - port: http
      path: /metrics
      interval: 30s
