apiVersion: v1
kind: ConfigMap
metadata:
  name: librechat-config
  namespace: librechat
data:
  librechat.yaml: |
    version: 1.2.8

    cache: false

    interface:
      # Privacy policy settings
      privacyPolicy:
        externalUrl: 'https://librechat.ai/privacy-policy'
        openNewTab: true

      # Terms of service
      termsOfService:
        externalUrl: 'https://librechat.ai/tos'
        openNewTab: true

    mcpServers:
      tool-gateway:
        type: streamable-http
        url: "http://tool-gateway.tool-gateway/mcp"

    endpoints:
      custom:
        - name: "AI Gateway"
          apiKey: "not-needed"
          baseURL: "http://ai-gateway.ai-gateway"
          models:
            default: [ "" ]
            fetch: true
          titleConvo: true
          titleModel: "gemini/gemini-2.5-flash-lite"
          summarize: false
          summaryModel: "gemini/gemini-2.5-flash-lite"
          forcePrompt: false

        - name: "AI Gateway with PII guards"
          apiKey: "not-needed"
          baseURL: "http://ai-gateway-pii.ai-gateway"
          models:
            default: [ "" ]
            fetch: true
          titleConvo: true
          titleModel: "gemini/gemini-2.5-flash-lite"
          summarize: false
          summaryModel: "gemini/gemini-2.5-flash-lite"
          forcePrompt: false

        - name: "Agent Gateway"
          apiKey: "not-needed"
          baseURL: "http://agent-gateway.agent-gateway"
          models:
            default: [ "" ]
            fetch: true
          titleConvo: false
          summarize: false
          forcePrompt: false
          addParams:
            # Agent Gateway does not support streaming yet
            disableStreaming: true
          headers:
            X-Conversation-ID: "{{LIBRECHAT_BODY_CONVERSATIONID}}"
            X-Parent-Message-ID: "{{LIBRECHAT_BODY_PARENTMESSAGEID}}"
            X-Message-ID: "{{LIBRECHAT_BODY_MESSAGEID}}"
