apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vcluster-template # This name will be replaced by the overlay
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: vcluster
      version: "0.30.0"
      sourceRef:
        kind: HelmRepository
        name: vcluster
        namespace: flux-system
  # see https://www.vcluster.com/docs/vcluster/configure/vcluster-yaml/ (this is the vcluster.yaml)
  values:
    # Enable external access via LoadBalancer
    controlPlane:
      service:
        enabled: true
        spec:
          type: LoadBalancer
    networking:
      replicateServices:
        fromHost:
          - from: monitoring/lgtm
            to: monitoring/lgtm
          - from: observability-dashboard/observability-dashboard
            to: observability-dashboard/observability-dashboard
    sync:
      fromHost:
        secrets:
          enabled: true
          mappings:
            byName:
              "showcase-news/*": "showcase-news/*"
